// <auto-generated />
using EKostApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EKostApi.Migrations
{
    [DbContext(typeof(EkostContext))]
    [Migration("20230731160637_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EKostApi.Models.DetailKost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KostId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("QtyRoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KostId");

                    b.HasIndex("OwnerId");

                    b.ToTable("DetailKosts");
                });

            modelBuilder.Entity("EKostApi.Models.DetailOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OwnerAccountUsername")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountUsername");

                    b.HasIndex("OwnerId");

                    b.ToTable("DetailOwners");
                });

            modelBuilder.Entity("EKostApi.Models.DetailUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserAccountUsername")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountUsername");

                    b.HasIndex("UserId");

                    b.ToTable("DetailUsers");
                });

            modelBuilder.Entity("EKostApi.Models.Kost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KostAdressId")
                        .HasColumnType("int");

                    b.Property<string>("KostName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KostPrice")
                        .HasColumnType("int");

                    b.Property<int>("KostTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KostAdressId");

                    b.HasIndex("KostTypeId");

                    b.ToTable("Kost");
                });

            modelBuilder.Entity("EKostApi.Models.KostAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KostAdress");
                });

            modelBuilder.Entity("EKostApi.Models.KostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TypeKost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("kostTypes");
                });

            modelBuilder.Entity("EKostApi.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("EKostApi.Models.OwnerAccount", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Username");

                    b.ToTable("OwnerAccounts");
                });

            modelBuilder.Entity("EKostApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EKostApi.Models.UserAccount", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Username");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("EKostApi.Models.DetailKost", b =>
                {
                    b.HasOne("EKostApi.Models.Kost", "Kost")
                        .WithMany()
                        .HasForeignKey("KostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EKostApi.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kost");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EKostApi.Models.DetailOwner", b =>
                {
                    b.HasOne("EKostApi.Models.OwnerAccount", "OwnerAccount")
                        .WithMany()
                        .HasForeignKey("OwnerAccountUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EKostApi.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("EKostApi.Models.DetailUser", b =>
                {
                    b.HasOne("EKostApi.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EKostApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("EKostApi.Models.Kost", b =>
                {
                    b.HasOne("EKostApi.Models.KostAdress", "KostAdress")
                        .WithMany()
                        .HasForeignKey("KostAdressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EKostApi.Models.KostType", "KostType")
                        .WithMany()
                        .HasForeignKey("KostTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KostAdress");

                    b.Navigation("KostType");
                });
#pragma warning restore 612, 618
        }
    }
}
