// <auto-generated />
using EKostApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EKostApi.Migrations
{
    [DbContext(typeof(EkostContext))]
    [Migration("20230801083315_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EKostApi.Models.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EKostApi.Models.DetailAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountUsername")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountUsername");

                    b.ToTable("DetailAccount");
                });

            modelBuilder.Entity("EKostApi.Models.DetailKost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountUsername")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("KostId")
                        .HasColumnType("int");

                    b.Property<int>("QtyRoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountUsername");

                    b.HasIndex("KostId");

                    b.ToTable("DetailKosts");
                });

            modelBuilder.Entity("EKostApi.Models.Kost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KostAdressId")
                        .HasColumnType("int");

                    b.Property<string>("KostName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KostPrice")
                        .HasColumnType("int");

                    b.Property<int>("KostTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KostAdressId");

                    b.HasIndex("KostTypeId");

                    b.ToTable("Kost");
                });

            modelBuilder.Entity("EKostApi.Models.KostAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KostAdress");
                });

            modelBuilder.Entity("EKostApi.Models.KostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TypeKost")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("kostTypes");
                });

            modelBuilder.Entity("EKostApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EKostApi.Models.Account", b =>
                {
                    b.HasOne("EKostApi.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EKostApi.Models.DetailAccount", b =>
                {
                    b.HasOne("EKostApi.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountUsername");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EKostApi.Models.DetailKost", b =>
                {
                    b.HasOne("EKostApi.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountUsername");

                    b.HasOne("EKostApi.Models.Kost", "Kost")
                        .WithMany()
                        .HasForeignKey("KostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Kost");
                });

            modelBuilder.Entity("EKostApi.Models.Kost", b =>
                {
                    b.HasOne("EKostApi.Models.KostAdress", "KostAdress")
                        .WithMany()
                        .HasForeignKey("KostAdressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EKostApi.Models.KostType", "KostType")
                        .WithMany()
                        .HasForeignKey("KostTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KostAdress");

                    b.Navigation("KostType");
                });
#pragma warning restore 612, 618
        }
    }
}
